# 예외처리: `try`-`catch`
`try`: 실행되는 동안 에러가 발생할지 테스트하는 코드 블록

`catch`: `try` 블록에서 에러가 발생했을 때 실행되는 코드 블록

(+) `finally`: 예외 발생 여부와 상관없이 항상 실행되는 코드 블록

```java
public class Main {
  public static void main(String[] args) {
    try {
      int[] myNumbers = {1, 2, 3};
      System.out.println(myNumbers[10]);
    } catch (Exception e) {
      System.out.println("Something went wrong.");
    } finally {
      System.out.println("The 'try catch' is finished.");
    }
  }
}
```

# `throw`
사용자 정의 에러를 발생시킬 때 사용

**에러 타입**과 함께 사용: `FileNotFoundException`, `ArrayIndexOutOfBoundsException` 등

```java
public class Main {
  static void checkAge(int age) {
    if (age < 18) {
      throw new ArithmeticException("Access denied - You must be at least 18 years old.");
    }
    else {
      System.out.println("Access granted - You are old enough!");
    }
  }

  public static void main(String[] args) {
    checkAge(15); // 나이가 15인 경우 - 오류 발생
  }
}
```

## 오류, 예외 타입
|오류/예외|설명|
|-|-|
|`ArithmeticException`|잘못된 산술 연산(하위 에러들이 더 존재함, ZeroDivisionError, OverflowError 등)|
|`ArrayIndexOutOfBoundsException`|배열의 잘못된 인덱스 접근|
|`ClassNotFoundException`|클래스를 찾을 수 없을 때 발생|
|`FileNotFoundException`|파일이 존재하지 않을 때 발생|
|`InputMismatchException`|잘못된 타입의 입력이 주어졌을 때 발생|
|`IOException`|입출력 작업 실패 또는 인터럽트 시 발생|
|`NullPointerException`|null 참조를 사용하려고 할 때 발생|
|`NumberFormatException`|문자열을 숫자로 변환할 수 없을 때 발생|
|`StringIndexOutOfBoundsException`|문자열의 잘못된 인덱스 접근|

더 많은 예외 타입은 >> [문서](https://www.w3schools.com/java/java_ref_errors.asp) << 참조